name: Deploy to EC2 (HTTP)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Trigger Deploy Script on EC2
      run: |
        curl -X POST http://13.62.98.65:4000/deploy
